module.exports = {
  sourceDir: ".",
  artifactsDir: "web-ext-artifacts",
  ignoreFiles: [
    "docs",
    "docs/**",
    "web-ext-artifacts",
    "web-ext-artifacts/**",
    ".extension-build",
    ".extension-build/**",
    "dist",
    "dist/**",
    ".git",
    ".git/**",
    ".github",
    ".github/**",
    ".gitignore",
    "CONTRIBUTING.md",
    "web-ext.config.cjs",
    ".DS_Store",
    "*.zip",
  ],
};
